package:
  name: "ash"
  version: "0.1.0"

source:
  git_rev: v0.1.0
  git_url: https://github.com/GiulioRossetti/ASH

requirements:
  host:
    - python
    - setuptools
  build:
    - python
    - setuptools
  run:
    - python>=3.9
    - numpy
    - halp

about:
  home: https://github.com/GiulioRossetti/ASH
  license: BSD-2-Clause
  license_familY: BSD
  license_file: LICENSE
  summary: "Attributed Stream Hypergraph library"

extra:
  recipe-maintainers:
    - GiulioRossetti
